import {
  BookBookmark, FilmStrip, Microphone, GameController, Scales,
  Newspaper, UsersThree, CalendarDots, Lock, Sliders,
  Flask, ChatsCircle, CursorClick, VideoCamera, BookOpenText,
  SlidersHorizontal, Microscope, MaskHappy, Graph, Lightbulb,
  MonitorPlay, Books, TreeStructure, Question, Sparkle,
  TextAlignLeft, ClockCountdown, Rows, Table, ChartBar,
  ClipboardText, PencilLine, Wrench, TestTube, ChartLineUp,
  GitBranch, Code, Compass, Strategy, PaintBrush,
  CheckSquare, Clipboard, Timer, ListChecks, PenNib,
  ArrowsLeftRight, SquaresFour, ChatText, Target, Medal,
} from '@phosphor-icons/react'

export const RESOURCE_ICONS = {
  'engage:1':    BookBookmark,
  'engage:2':    FilmStrip,
  'engage:3':    Microphone,
  'engage:4':    GameController,
  'engage:5':    Scales,
  'engage:6':    Newspaper,
  'engage:7':    UsersThree,
  'engage:8':    CalendarDots,
  'engage:9':    Lock,
  'engage:10':   Sliders,

  'explore:1':   Flask,
  'explore:2':   ChatsCircle,
  'explore:3':   CursorClick,
  'explore:4':   VideoCamera,
  'explore:5':   BookOpenText,
  'explore:6':   SlidersHorizontal,
  'explore:7':   Microscope,
  'explore:8':   MaskHappy,
  'explore:9':   Graph,
  'explore:10':  Lightbulb,

  'explain:1':   MonitorPlay,
  'explain:2':   Books,
  'explain:3':   TreeStructure,
  'explain:4':   Question,
  'explain:5':   Sparkle,
  'explain:6':   TextAlignLeft,
  'explain:7':   ClockCountdown,
  'explain:8':   Rows,
  'explain:9':   Table,
  'explain:10':  ChartBar,

  'elaborate:1': ClipboardText,
  'elaborate:2': PencilLine,
  'elaborate:3': Wrench,
  'elaborate:4': TestTube,
  'elaborate:5': ChartLineUp,
  'elaborate:6': GitBranch,
  'elaborate:7': Code,
  'elaborate:8': Compass,
  'elaborate:9': Strategy,
  'elaborate:10':PaintBrush,

  'evaluate:1':  CheckSquare,
  'evaluate:2':  Clipboard,
  'evaluate:3':  Timer,
  'evaluate:4':  ListChecks,
  'evaluate:5':  PenNib,
  'evaluate:6':  ArrowsLeftRight,
  'evaluate:7':  SquaresFour,
  'evaluate:8':  ChatText,
  'evaluate:9':  Target,
  'evaluate:10': Medal,
}
