"""Curated LLM model allowlist — single source of truth for model entries.

Imported by model_catalog.py which builds the runtime catalog and exports
all public symbols. Do not import this file directly from outside llm/.
"""

CATALOG_ENTRIES = [
    # Groq — pricing=None means gratis (Groq doesn't charge per token).
    {
        "provider": "groq",
        "model_id": "llama-3.3-70b-versatile",
        "label": "Llama 3.3 70B (Groq)",
        "task": "texto",
        "pricing": None,
        "context_length": 128000,
        "active": True,
        "modality": "text",
    },
    {
        "provider": "groq",
        "model_id": "llama-3.1-8b-instant",
        "label": "Llama 3.1 8B (Groq)",
        "task": "texto",
        "pricing": None,
        "context_length": 128000,
        "active": True,
        "modality": "text",
    },
    {
        "provider": "groq",
        "model_id": "qwen/qwen3-32b",
        "label": "Qwen3 32B (Groq)",
        "task": "razonamiento",
        "pricing": None,
        "context_length": 128000,
        "active": True,
        "modality": "text",
    },
    {
        "provider": "groq",
        "model_id": "openai/gpt-oss-120b",
        "label": "GPT-OSS 120B (Groq)",
        "task": "orquestador",
        "pricing": None,
        "context_length": 128000,
        "active": True,
        "modality": "text",
    },
    # OpenRouter — pricing populated at startup from /api/v1/models.
    {
        "provider": "openrouter",
        "model_id": "deepseek/deepseek-v4-flash",
        "label": "DeepSeek V4 Flash (OpenRouter)",
        "task": "codigo",
        "pricing": None,
        "context_length": None,
        "active": True,
        "modality": "multimodal",
        "notes": "LiveCodeBench 91.6 / SWE-bench 79.0. Mejor seguimiento de reglas anidadas.",
    },
    {
        "provider": "openrouter",
        "model_id": "deepseek/deepseek-chat-v3.1",
        "label": "DeepSeek Chat V3.1 (OpenRouter)",
        "task": "codigo",
        "pricing": None,
        "context_length": None,
        "active": True,
        "modality": "text",
    },
    {
        "provider": "openrouter",
        "model_id": "qwen/qwen3-coder",
        "label": "Qwen3 Coder (OpenRouter)",
        "task": "codigo",
        "pricing": None,
        "context_length": None,
        "active": True,
        "modality": "text",
    },
    {
        "provider": "openrouter",
        "model_id": "qwen/qwen3-coder:free",
        "label": "Qwen3 Coder (OpenRouter · free)",
        "task": "codigo",
        "pricing": None,
        "context_length": None,
        "active": True,
        "modality": "text",
    },
    {
        "provider": "openrouter",
        "model_id": "deepseek/deepseek-v4-flash",
        "label": "DeepSeek V4 Flash (OpenRouter)",
        "task": "texto",
        "pricing": None,
        "context_length": None,
        "active": True,
        "modality": "text",
    },
    {
        "provider": "openrouter",
        "model_id": "deepseek/deepseek-chat-v3.1",
        "label": "DeepSeek Chat V3.1 (OpenRouter)",
        "task": "texto",
        "pricing": None,
        "context_length": None,
        "active": True,
        "modality": "text",
    },
    {
        "provider": "openrouter",
        "model_id": "meta-llama/llama-3.3-70b-instruct:free",
        "label": "Llama 3.3 70B (OpenRouter · free)",
        "task": "texto",
        "pricing": None,
        "context_length": None,
        "active": True,
        "modality": "text",
    },
    # OpenRouter meta-models — special routers, not single models.
    # openrouter/auto: free auto-router; sends the prompt to whichever free model
    # OpenRouter considers best for the task on that turn. Zero direct cost.
    {
        "provider": "openrouter",
        "model_id": "openrouter/auto",
        "label": "Auto (OpenRouter · mejor modelo gratis)",
        "task": "texto",
        "pricing": None,
        "context_length": None,
        "active": True,
        "modality": "text",
        "notes": "Enruta automáticamente al mejor modelo gratuito disponible para la tarea.",
    },
    {
        "provider": "openrouter",
        "model_id": "openrouter/auto",
        "label": "Auto (OpenRouter · mejor modelo gratis)",
        "task": "orquestador",
        "pricing": None,
        "context_length": None,
        "active": True,
        "modality": "text",
        "notes": "Enruta automáticamente al mejor modelo gratuito disponible para la tarea.",
    },
    {
        "provider": "openrouter",
        "model_id": "openrouter/auto",
        "label": "Auto (OpenRouter · mejor modelo gratis)",
        "task": "razonamiento",
        "pricing": None,
        "context_length": None,
        "active": True,
        "modality": "text",
        "notes": "Enruta automáticamente al mejor modelo gratuito disponible para la tarea.",
    },
    # openrouter/fusion: ensembles multiple models — higher quality but slower and
    # more expensive (each call hits several models internally).
    {
        "provider": "openrouter",
        "model_id": "openrouter/fusion",
        "label": "Fusion (OpenRouter · ensemble de modelos)",
        "task": "texto",
        "pricing": None,
        "context_length": None,
        "active": True,
        "modality": "text",
        "notes": "Fusiona varios modelos para mayor calidad. Más lento y costoso.",
    },
    # OpenCode Go — personal subscription (bearer token). No API refresh needed;
    # model list is static and verified manually via GET /v1/models.
    {
        "provider": "opencode",
        "model_id": "deepseek-v4-pro",
        "label": "DeepSeek V4 Pro (OpenCode Go)",
        "task": "codigo",
        "pricing": None,
        "context_length": 163840,
        "active": True,
        "modality": "text",
    },
]
