"""Puertos estructurales del ciclo de vida de una OVA."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol

from ova.domain.editor import EditorOva, EditorPhase, EditorVersion
from ova.domain.model import Ova, OvaDuplicateSource, OvaPhase


class OvaLifecycleRepository(Protocol):
    def get_active(self, ova_id: str) -> Ova | None: ...

    def get_trashed(self, ova_id: str) -> Ova | None: ...

    def count_trashed(self, owner_id: str | None) -> int: ...

    def list_trashed(self, owner_id: str | None, offset: int, limit: int) -> list[Ova]: ...

    def update_metadata(self, ova_id: str, title: str, description: str | None) -> None: ...

    def move_to_trash(self, ova_id: str, deleted_at: datetime) -> None: ...

    def restore(self, ova_id: str) -> None: ...

    def stage_permanent_delete(self, ova_id: str) -> None: ...

    def commit(self, operation: str) -> None: ...


class ScormPackageCleaner(Protocol):
    def delete(self, file_path: str | None, storage_key: str | None) -> None: ...


class OvaCreationRepository(Protocol):
    def create_ova(
        self, owner_id: str, title: str, description: str | None, status: str
    ) -> str: ...

    def create_version(self, ova_id: str, version_number: int, prompt: str) -> str: ...

    def add_phases(self, version_id: str, phases: tuple[OvaPhase, ...]) -> None: ...

    def set_scorm_package(
        self,
        ova_id: str,
        version_id: str,
        storage_key: str | None,
        file_path: str | None,
    ) -> None: ...

    def tie_uploads_to_ova(self, upload_ids: tuple[str, ...], ova_id: str) -> None: ...

    def commit(self, operation: str) -> None: ...


class OvaDuplicationRepository(Protocol):
    def get_duplicate_source(self, ova_id: str) -> OvaDuplicateSource | None: ...

    def next_copy_title(self, base_title: str, owner_id: str) -> str: ...

    def create_ova(
        self, owner_id: str, title: str, description: str | None, status: str
    ) -> str: ...

    def create_version(self, ova_id: str, version_number: int, prompt: str) -> str: ...

    def add_phases(self, version_id: str, phases: tuple[OvaPhase, ...]) -> None: ...

    def set_current_version(self, ova_id: str, version_id: str) -> None: ...

    def commit(self, operation: str) -> None: ...


class OvaEditorRepository(Protocol):
    def get_ova(self, ova_id: str) -> EditorOva | None: ...

    def get_or_create_active_version(self, ova: EditorOva) -> EditorVersion: ...

    def get_phase(self, phase_id: str, version_id: str) -> EditorPhase | None: ...

    def list_phases(self, version_id: str) -> tuple[EditorPhase, ...]: ...

    def get_phases(self, phase_ids: tuple[str, ...], version_id: str) -> tuple[EditorPhase, ...]: ...

    def reorder(self, reorders: tuple[tuple[str, int], ...]) -> None: ...

    def create_next_version(
        self, ova: EditorOva, active: EditorVersion, phases: tuple[EditorPhase, ...]
    ) -> EditorVersion: ...

    def set_current_version(self, ova_id: str, version_id: str) -> None: ...

    def rebuild_scorm(self, ova_id: str, version_id: str, user_id: str) -> None: ...

    def record_micro_version(self, phase_id: str, ova_id: str, content: str) -> None: ...

    def count_phases(self, version_id: str, phase_type: str) -> int: ...

    def next_phase_order(self, version_id: str, phase_type: str) -> int: ...

    def add_phase(
        self, version_id: str, phase_type: str, phase_order: int, content: str
    ) -> EditorPhase: ...

    def list_versions(self, ova_id: str) -> tuple[EditorVersion, ...]: ...

    def get_version(self, version_id: str, ova_id: str, with_phases: bool = False) -> EditorVersion | None: ...

    def activate_version(self, ova_id: str, version_id: str) -> None: ...

    def commit(self, operation: str) -> None: ...
