"""Dominio puro del editor visual."""

from editor.domain.errors import (
    EditorDomainError,
    GuardRejectedError,
    InvalidBlockError,
    UnfeasibleIntentError,
)
from editor.domain.feasibility import (
    check_add_type_supported,
    check_ambiguous_deictics,
    check_destination_reference_feasibility,
    check_non_existent_raw_types,
    check_target_feasibility,
    display_plural_type_name,
    display_type_name,
)
from editor.domain.guardrails import (
    INAPPROPRIATE_LANGUAGE_MESSAGE,
    MASS_DELETE_MESSAGE,
    OUT_OF_SCOPE_MESSAGE,
    check_deterministic_guard,
    extract_core_request,
    get_guard_telemetry,
    record_guard_rejection,
    strip_control_characters,
)
from editor.domain.model import (
    ApplyIntentResult,
    EditResult,
    GuardCheckResult,
    Intent,
    IntentBlockRef,
    IntentDestino,
    IntentDestinoRef,
    IntentTrace,
    ResourceBlock,
)
from editor.domain.normalization import (
    expand_enclitics,
    has_multiple_actions,
    is_generative_content_request,
    levenshtein,
    normalize_search_string,
    normalize_text,
    normalize_type,
    parse_ordinal_value,
    reduce_repeated_chars,
)
from editor.domain.reducer import (
    apply_intent,
    find_block_by_content_or_title,
    find_target_block_index,
    format_block_description,
    get_block_snippet,
    map_type_to_tag,
)
from editor.domain.render import render_block, render_blocks_to_html
from editor.domain.segmentation import (
    extract_deterministic_action,
    extract_deterministic_destination,
    extract_deterministic_ordinal,
    extract_deterministic_type,
    split_object_and_destination,
)

__all__ = [
    "ApplyIntentResult",
    "EditResult",
    "EditorDomainError",
    "GuardCheckResult",
    "GuardRejectedError",
    "INAPPROPRIATE_LANGUAGE_MESSAGE",
    "Intent",
    "IntentBlockRef",
    "IntentDestino",
    "IntentDestinoRef",
    "IntentTrace",
    "InvalidBlockError",
    "MASS_DELETE_MESSAGE",
    "OUT_OF_SCOPE_MESSAGE",
    "ResourceBlock",
    "UnfeasibleIntentError",
    "apply_intent",
    "check_add_type_supported",
    "check_ambiguous_deictics",
    "check_destination_reference_feasibility",
    "check_deterministic_guard",
    "check_non_existent_raw_types",
    "check_target_feasibility",
    "display_plural_type_name",
    "display_type_name",
    "expand_enclitics",
    "extract_core_request",
    "extract_deterministic_action",
    "extract_deterministic_destination",
    "extract_deterministic_ordinal",
    "extract_deterministic_type",
    "find_block_by_content_or_title",
    "find_target_block_index",
    "format_block_description",
    "get_block_snippet",
    "get_guard_telemetry",
    "has_multiple_actions",
    "is_generative_content_request",
    "levenshtein",
    "map_type_to_tag",
    "normalize_search_string",
    "normalize_text",
    "normalize_type",
    "parse_ordinal_value",
    "record_guard_rejection",
    "reduce_repeated_chars",
    "render_block",
    "render_blocks_to_html",
    "split_object_and_destination",
    "strip_control_characters",
]
