import {
  ArrowClockwiseIcon,
  ArrowCounterClockwiseIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  BlueprintIcon,
  BookOpenIcon,
  BrainIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpIcon,
  ChartBarIcon,
  ChartLineIcon,
  ChatCircleIcon,
  ChatTextIcon,
  CheckCircleIcon,
  CheckIcon,
  CheckSquareIcon,
  CircleIcon,
  ClipboardTextIcon,
  ClockCounterClockwiseIcon,
  ClockIcon,
  CloudArrowUpIcon,
  CodeIcon,
  CompassIcon,
  CopyIcon,
  CpuIcon,
  DesktopIcon,
  DoorIcon,
  DotsSixVerticalIcon,
  DotsThreeVerticalIcon,
  DownloadSimpleIcon,
  EnvelopeIcon,
  EnvelopeSimpleIcon,
  ExamIcon,
  EyeIcon,
  EyeSlashIcon,
  FileTextIcon,
  FilmStripIcon,
  FlaskIcon,
  FolderIcon,
  GameControllerIcon,
  GearIcon,
  GitBranchIcon,
  GraduationCapIcon,
  GraphIcon,
  HammerIcon,
  HouseIcon,
  type Icon as PhosphorIcon,
  type IconWeight,
  ImageIcon,
  InfoIcon,
  LightbulbIcon,
  LightningIcon,
  LinkIcon,
  ListChecksIcon,
  ListIcon,
  LockIcon,
  LockOpenIcon,
  MagicWandIcon,
  MagnifyingGlassIcon,
  MagnifyingGlassMinusIcon,
  MicrophoneIcon,
  MonitorIcon,
  MoonIcon,
  NewspaperIcon,
  PaletteIcon,
  PaperclipIcon,
  PaperPlaneTiltIcon,
  PencilSimpleIcon,
  PlusIcon,
  PlusSquareIcon,
  PresentationChartIcon,
  PuzzlePieceIcon,
  QuestionIcon,
  RobotIcon,
  ScalesIcon,
  SelectionIcon,
  ShieldCheckIcon,
  ShieldIcon,
  ShieldSlashIcon,
  SidebarIcon,
  SidebarSimpleIcon,
  SignOutIcon,
  SlidersHorizontalIcon,
  SparkleIcon,
  SpinnerIcon,
  SquareHalfIcon,
  SquaresFourIcon,
  StackIcon,
  StarIcon,
  StrategyIcon,
  SunIcon,
  TableIcon,
  TargetIcon,
  TextAaIcon,
  TextTIcon,
  TimerIcon,
  TrashIcon,
  TreeStructureIcon,
  TrophyIcon,
  UploadSimpleIcon,
  UserCircleIcon,
  UserIcon,
  UsersIcon,
  UsersThreeIcon,
  VideoCameraIcon,
  VideoIcon,
  WarningCircleIcon,
  WarningIcon,
  WrenchIcon,
  XIcon,
} from "@phosphor-icons/react";

import { cn } from "@/core/lib/cn";

/**
 * Explicit name → component map: only these icons end up in the bundle
 * (the Angular app shipped the whole Phosphor web font for ~100 glyphs).
 */
const ICONS = {
  "arrow-clockwise": ArrowClockwiseIcon,
  "arrow-counter-clockwise": ArrowCounterClockwiseIcon,
  "arrow-left": ArrowLeftIcon,
  "arrow-right": ArrowRightIcon,
  blueprint: BlueprintIcon,
  "book-open": BookOpenIcon,
  brain: BrainIcon,
  "caret-down": CaretDownIcon,
  "caret-left": CaretLeftIcon,
  "caret-right": CaretRightIcon,
  "caret-up": CaretUpIcon,
  "chart-bar": ChartBarIcon,
  "chart-line": ChartLineIcon,
  "chat-circle": ChatCircleIcon,
  "chat-text": ChatTextIcon,
  check: CheckIcon,
  "check-circle": CheckCircleIcon,
  "check-square": CheckSquareIcon,
  circle: CircleIcon,
  "clipboard-text": ClipboardTextIcon,
  clock: ClockIcon,
  "clock-counter-clockwise": ClockCounterClockwiseIcon,
  "cloud-arrow-up": CloudArrowUpIcon,
  code: CodeIcon,
  compass: CompassIcon,
  copy: CopyIcon,
  cpu: CpuIcon,
  desktop: DesktopIcon,
  door: DoorIcon,
  "dots-six-vertical": DotsSixVerticalIcon,
  "dots-three-vertical": DotsThreeVerticalIcon,
  "download-simple": DownloadSimpleIcon,
  envelope: EnvelopeIcon,
  "envelope-simple": EnvelopeSimpleIcon,
  exam: ExamIcon,
  eye: EyeIcon,
  "eye-slash": EyeSlashIcon,
  "file-text": FileTextIcon,
  "film-strip": FilmStripIcon,
  flask: FlaskIcon,
  folder: FolderIcon,
  "game-controller": GameControllerIcon,
  gear: GearIcon,
  "git-branch": GitBranchIcon,
  "graduation-cap": GraduationCapIcon,
  graph: GraphIcon,
  hammer: HammerIcon,
  house: HouseIcon,
  image: ImageIcon,
  info: InfoIcon,
  lightbulb: LightbulbIcon,
  lightning: LightningIcon,
  link: LinkIcon,
  list: ListIcon,
  "list-checks": ListChecksIcon,
  lock: LockIcon,
  "lock-open": LockOpenIcon,
  "magic-wand": MagicWandIcon,
  "magnifying-glass": MagnifyingGlassIcon,
  "magnifying-glass-minus": MagnifyingGlassMinusIcon,
  microphone: MicrophoneIcon,
  monitor: MonitorIcon,
  moon: MoonIcon,
  newspaper: NewspaperIcon,
  palette: PaletteIcon,
  "paper-plane-tilt": PaperPlaneTiltIcon,
  paperclip: PaperclipIcon,
  "pencil-simple": PencilSimpleIcon,
  plus: PlusIcon,
  "plus-square": PlusSquareIcon,
  "presentation-chart": PresentationChartIcon,
  "puzzle-piece": PuzzlePieceIcon,
  question: QuestionIcon,
  robot: RobotIcon,
  scales: ScalesIcon,
  selection: SelectionIcon,
  shield: ShieldIcon,
  "shield-check": ShieldCheckIcon,
  "shield-slash": ShieldSlashIcon,
  sidebar: SidebarIcon,
  "sidebar-simple": SidebarSimpleIcon,
  "sign-out": SignOutIcon,
  "sliders-horizontal": SlidersHorizontalIcon,
  sparkle: SparkleIcon,
  spinner: SpinnerIcon,
  "square-half": SquareHalfIcon,
  "squares-four": SquaresFourIcon,
  stack: StackIcon,
  star: StarIcon,
  strategy: StrategyIcon,
  sun: SunIcon,
  table: TableIcon,
  target: TargetIcon,
  "text-aa": TextAaIcon,
  "text-t": TextTIcon,
  timer: TimerIcon,
  trash: TrashIcon,
  "tree-structure": TreeStructureIcon,
  trophy: TrophyIcon,
  "upload-simple": UploadSimpleIcon,
  user: UserIcon,
  "user-circle": UserCircleIcon,
  users: UsersIcon,
  "users-three": UsersThreeIcon,
  video: VideoIcon,
  "video-camera": VideoCameraIcon,
  warning: WarningIcon,
  "warning-circle": WarningCircleIcon,
  wrench: WrenchIcon,
  x: XIcon,
} satisfies Record<string, PhosphorIcon>;

export type IconName = keyof typeof ICONS;

interface IconProps {
  /** Phosphor slug, with or without the legacy `ph-` prefix (e.g. "gear", "ph-gear"). */
  name: IconName | (string & {});
  weight?: IconWeight;
  /** Optional Tailwind text-size class ("text-lg"): icons render at 1em. */
  size?: string;
  className?: string;
  /** Accessible label; without it the icon is decorative (aria-hidden). */
  label?: string;
}

export function Icon({ name, weight = "regular", size, className, label }: Readonly<IconProps>) {
  const slug = name.startsWith("ph-") ? name.slice(3) : name;
  const Glyph: PhosphorIcon = Object.hasOwn(ICONS, slug) ? ICONS[slug as IconName] : QuestionIcon;
  return (
    <Glyph
      size="1em"
      weight={weight}
      className={cn("inline-block shrink-0", size, className)}
      aria-hidden={label ? undefined : true}
      aria-label={label}
      role={label ? "img" : undefined}
    />
  );
}
