import {
  ArrowClockwiseIcon,
  ArrowCounterClockwiseIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  BlueprintIcon,
  BookOpenIcon,
  BrainIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretUpIcon,
  ChartLineIcon,
  ChatCircleIcon,
  ChatTextIcon,
  CheckIcon,
  CheckSquareIcon,
  ClipboardTextIcon,
  ClockCounterClockwiseIcon,
  CloudArrowUpIcon,
  CodeIcon,
  CompassIcon,
  CopyIcon,
  CpuIcon,
  DesktopIcon,
  DoorIcon,
  DotsSixVerticalIcon,
  DotsThreeVerticalIcon,
  DownloadSimpleIcon,
  EnvelopeIcon,
  ExamIcon,
  FilmStripIcon,
  FlaskIcon,
  GameControllerIcon,
  GitBranchIcon,
  GraduationCapIcon,
  GraphIcon,
  HammerIcon,
  type Icon as PhosphorIcon,
  ImageIcon,
  InfoIcon,
  LightbulbIcon,
  LightningIcon,
  LinkIcon,
  ListChecksIcon,
  LockIcon,
  LockOpenIcon,
  MagicWandIcon,
  MagnifyingGlassMinusIcon,
  MicrophoneIcon,
  NewspaperIcon,
  PaperclipIcon,
  PaperPlaneTiltIcon,
  PencilSimpleIcon,
  PresentationChartIcon,
  ProhibitIcon,
  PuzzlePieceIcon,
  QuestionIcon,
  ScalesIcon,
  SelectionIcon,
  ShieldSlashIcon,
  SlidersHorizontalIcon,
  SparkleIcon,
  SpinnerIcon,
  SquareHalfIcon,
  SquaresFourIcon,
  StackIcon,
  StarIcon,
  StrategyIcon,
  TableIcon,
  TargetIcon,
  TextAaIcon,
  TextTIcon,
  TimerIcon,
  TreeStructureIcon,
  TrophyIcon,
  UploadSimpleIcon,
  UserIcon,
  UsersThreeIcon,
  VideoCameraIcon,
  VideoIcon,
  WrenchIcon,
} from "@phosphor-icons/react";

/** Juego extendido de iconos: cargado en idle/primera necesidad (no en el arranque). */
export const LAZY_ICONS = {
  "arrow-clockwise": ArrowClockwiseIcon,
  "arrow-counter-clockwise": ArrowCounterClockwiseIcon,
  "arrow-left": ArrowLeftIcon,
  "arrow-right": ArrowRightIcon,
  blueprint: BlueprintIcon,
  "book-open": BookOpenIcon,
  brain: BrainIcon,
  "caret-down": CaretDownIcon,
  "caret-left": CaretLeftIcon,
  "caret-up": CaretUpIcon,
  "chart-line": ChartLineIcon,
  "chat-circle": ChatCircleIcon,
  "chat-text": ChatTextIcon,
  check: CheckIcon,
  "check-square": CheckSquareIcon,
  "clipboard-text": ClipboardTextIcon,
  "clock-counter-clockwise": ClockCounterClockwiseIcon,
  "cloud-arrow-up": CloudArrowUpIcon,
  code: CodeIcon,
  compass: CompassIcon,
  copy: CopyIcon,
  cpu: CpuIcon,
  desktop: DesktopIcon,
  door: DoorIcon,
  "dots-six-vertical": DotsSixVerticalIcon,
  "dots-three-vertical": DotsThreeVerticalIcon,
  "download-simple": DownloadSimpleIcon,
  envelope: EnvelopeIcon,
  exam: ExamIcon,
  "film-strip": FilmStripIcon,
  flask: FlaskIcon,
  "game-controller": GameControllerIcon,
  "git-branch": GitBranchIcon,
  "graduation-cap": GraduationCapIcon,
  graph: GraphIcon,
  hammer: HammerIcon,
  image: ImageIcon,
  info: InfoIcon,
  lightbulb: LightbulbIcon,
  lightning: LightningIcon,
  link: LinkIcon,
  "list-checks": ListChecksIcon,
  lock: LockIcon,
  "lock-open": LockOpenIcon,
  "magic-wand": MagicWandIcon,
  "magnifying-glass-minus": MagnifyingGlassMinusIcon,
  microphone: MicrophoneIcon,
  newspaper: NewspaperIcon,
  "paper-plane-tilt": PaperPlaneTiltIcon,
  paperclip: PaperclipIcon,
  "pencil-simple": PencilSimpleIcon,
  "presentation-chart": PresentationChartIcon,
  prohibit: ProhibitIcon,
  "puzzle-piece": PuzzlePieceIcon,
  question: QuestionIcon,
  scales: ScalesIcon,
  selection: SelectionIcon,
  "shield-slash": ShieldSlashIcon,
  "sliders-horizontal": SlidersHorizontalIcon,
  sparkle: SparkleIcon,
  spinner: SpinnerIcon,
  "square-half": SquareHalfIcon,
  "squares-four": SquaresFourIcon,
  stack: StackIcon,
  star: StarIcon,
  strategy: StrategyIcon,
  table: TableIcon,
  target: TargetIcon,
  "text-aa": TextAaIcon,
  "text-t": TextTIcon,
  timer: TimerIcon,
  "tree-structure": TreeStructureIcon,
  trophy: TrophyIcon,
  "upload-simple": UploadSimpleIcon,
  user: UserIcon,
  "users-three": UsersThreeIcon,
  video: VideoIcon,
  "video-camera": VideoCameraIcon,
  wrench: WrenchIcon,
} satisfies Record<string, PhosphorIcon>;
